services:
  - type: web
    name: telegram-bot
    env: python
    plan: free
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TOKEN
        sync: false
      - key: WEBHOOK_URL
        sync: false
